import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://subhammart.airopos.com/');
  await page.goto('https://subhammart.airopos.com/login');
  await page.getByRole('textbox', { name: 'Phone number or username' }).fill('9000000000');
  await page.getByRole('button', { name: 'Send OTP' }).click();
  await page.getByRole('textbox', { name: 'Please enter OTP character 1' }).fill('1');
  await page.getByRole('textbox', { name: 'Please enter OTP character 2' }).fill('2');
  await page.getByRole('textbox', { name: 'Please enter OTP character 3' }).fill('3');
  await page.getByRole('textbox', { name: 'Please enter OTP character 4' }).fill('4');
  await page.getByRole('textbox', { name: 'Please enter OTP character 5' }).fill('5');
  await page.getByRole('textbox', { name: 'Please enter OTP character 6' }).fill('6');
  await page.getByRole('button', { name: 'Open ERP' }).click();
  await page.getByRole('complementary').getByText('Master Data').click();
  await page.getByRole('button', { name: 'Add SKU' }).click();
  await page.getByRole('textbox', { name: 'Enter barcode or generate' }).fill('877977777777abs=-0000000098*88888');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Mantra').click();
  await page.locator('#input-v-112').click();
  await page.getByText('Almond').click();
  await page.locator('#input-v-129').click();
  await page.getByText('12W').click();
  await page.locator('#input-v-116').click();
  await page.getByRole('option', { name: 'Kg', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter Unit Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Unit Value' }).fill('1');
  await page.locator('#input-v-133').click();
  await page.locator('#v-menu-v-135').getByText('Mantra').click();
  await page.getByRole('textbox', { name: 'Enter HSN Code' }).click();
  await page.getByRole('textbox', { name: 'Enter HSN Code' }).fill('12345');
  await page.getByRole('textbox', { name: 'Close' }).click();
  await page.getByText('5', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
});